branch-defaults:
  master:
    environment: marisabernard-prod
    group_suffix: null
environment-defaults:
  marisabernard-dev:
    branch: null
    repository: null
global:
  application_name: marisabernard
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
